### ISSUE TITLE
Question: Storing data in the app

### ISSUE THREAD

**Issue by warmachinesocial** [LibrePass/LibrePass-iOS#5]
Want to ask you that why don't we store the cipher using core data or swift data?

**Comment by aeoliux** [comment]
Why would we?

**Comment by warmachinesocial** [comment]
> Why would we?

1. If we want user to use the app without network connectivity
2. If we don't store them then are we wanting to up the db every time? However when we multiple devices we could fall into concurrency issues though i haven't looked much into the  entire codebase.
3. Every time when the cipher gets updated we only need to check for the network connectivity and make sure that is the user authenticated or not.

**Comment by aeoliux** [comment]
If you read the code, you would know that we use UserDefaults to store data. And it works, so why would we have to change the way

**Comment by warmachinesocial** [comment]
Yes I just read it now, user defaults is meant for something small like state changes on top of that we have to store either in keychain or a database using coredata. I would have to say that currently it's a wrong approach.

**Comment by aeoliux** [comment]
Ok. If you really want it, implement it.

**Comment by aeoliux** [comment]
@warmachinesocial I'm cleaning up code and adopting new API, so I can implement it. After I pull changes from newAPI branch, the code can be much different.

**Comment by warmachinesocial** [comment]
I have made a refactoring branch on code to show swiftui view and viewmodel. Plus at this stage I have removed the pods library and used swift package library, very few changes to it. So just want to confirm with you if you're fine it?

**Comment by aeoliux** [comment]
I don't want to change too much at the same time. Now I'm totally changing the way how app works because of SwiftData. For now LibrePassAPI handles data saving, but I need to completely make API separate from saving data and I have to move it to SwiftUI views. Sounds easy, but this app isn't prepared for it at all. After that, I will look what you did. At the moment I don't have real iOS device (I'm going to buy one), so I can't test biometrical authentication and QR code scanner. That's what I really need, not refactoring code. I would really appreciate if you could implement it (if you have real iOS device).

**Comment by warmachinesocial** [comment]
@aeoliux No worries I would try my best to put the features slowly and I would still work on my branch, when it gets ready will raise the PR

**Comment by aeoliux** [comment]
@warmachinesocia I have implemented SwiftData, so should this issue be closed?
