### ISSUE TITLE
Feature Request: Add Search Functionality to iOS App

### ISSUE THREAD

**Issue by OmarNazzal150** [LibrePass/LibrePass-iOS#7]
Hello LibrePass Team,

I hope this message finds you well. I've been using the LibrePass iOS app and find it incredibly useful for managing my passwords securely. However, I noticed that the app currently lacks a search feature, which can be inconvenient when trying to quickly find specific passwords.

I kindly request that you consider adding a search functionality to the iOS app. This would greatly enhance the user experience and make it even more efficient to manage passwords on the go.

Additionally, I have a question: Does the LibrePass app work on iPad as well? I'd love to use it across all my devices.

Thank you for your hard work on this project, and I appreciate your attention to user feedback!

Best regards,

**Comment by aeoliux** [comment]
@OmarNazzal150 I released version 1.3.0 with search functionality and I added iPads as target and it is... usable. If you are going to update from 1.2.1, make sure to sync everything, because since 1.2.2 app has been storing ciphers in a different way.

If everything works fine for you, please close this issue.

**Comment by OmarNazzal150** [comment]
I don't have an iPhone or ipad. I have an android phone but thanks for adding search functionality. Closing this issue now.
